# .properties ???? ??????? .yml ??? ??

server:
  port: 8000
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mustache:
    expose-session-attributes: true # 모든 session attribute를 template에 병합하기 전 포함시켜야하는 지 여부
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul #DB연결정보 설정
    username: bin #DB 계정 설정
    password: bin1234 # DB 비밀번호 설정

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # hibernate를 사용해서 DDL을 생성하기 위함
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #PhysicalNamingStrategyStandardImpl : ??? ??? ??? ???? ??
      use-new-id-generator-mappings: false # jpa? ?? ?? ??? ???? ?? (strategy = GenerationType.IDENTITY) //IDENTITY : ?????? ??? DB? ??? ??? ????.
    show-sql: true  #hibernate가 실행한 SQL 쿼리문을 보기 위함
    properties:
      hibernate.format_sql: true #???? ??????? ???? ???? ????.

  jackson:
    serialization:
      fail-on-empty-beans: false