# .properties ???? ??????? .yml ??? ??

server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mustache:
    expose-session-attributes: true
  mvc:
    view:
      prefix:
      suffix:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: bin
    password: bin1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #PhysicalNamingStrategyStandardImpl : ??? ??? ??? ???? ??
      use-new-id-generator-mappings: false # jpa? ?? ?? ??? ???? ?? (strategy = GenerationType.IDENTITY) //IDENTITY : ?????? ??? DB? ??? ??? ????.
    show-sql: true  #???? ???? ???? ????.
    properties:
      hibernate.format_sql: true #???? ??????? ???? ???? ????.

  jackson:
    serialization:
      fail-on-empty-beans: false